
# version: '3'

# services:
#   web:
#     build: .
#     command: bash -c "python manage.py migrate && python manage.py runserver"
#     container_name: PerformanceTracker
#     volumes:
#       - .:/code
#     ports:
#       - "8000:8000"
#     depends_on:
#       - redis

#   celery-worker:
#     build: .
#     command: celery -A PerformanceTracker worker --loglevel=info
#     volumes:
#       - .:/code
#     depends_on:
#       - redis

#   celery-beat:
#     build: .
#     command: celery -A PerformanceTracker beat --loglevel=info
#     volumes:
#       - .:/code
#     depends_on:
#       - redis

#   redis:
#     image: redis:latest
#     ports:
#       - '6379:6379'
#     environment:
#       TZ: "Asia/Kolkata"



version: '3'

services:
  web:
    build: .
    command: bash -c "python manage.py migrate && python manage.py runserver"
    container_name: PerformanceTracker
    volumes:
      - .:/code
    ports:
      - "8000:8000"
    depends_on:
      - redis
      - postgres

  celery-worker:
    build: .
    command: celery -A PerformanceTracker worker --loglevel=info
    volumes:
      - .:/code
    depends_on:
      - redis
      - postgres

  celery-beat:
    build: .
    command: celery -A PerformanceTracker beat --loglevel=info
    volumes:
      - .:/code
    depends_on:
      - redis
      - postgres

  redis:
    image: redis:latest
    ports:
      - '6379:6379'
    environment:
      TZ: "Asia/Kolkata"

  postgres:
    image: postgres:latest
    ports:
      - '5432:5432'
    environment:
      - POSTGRES_USER=myuser
      - POSTGRES_PASSWORD=mypassword
      - POSTGRES_DB=mydatabase
