
version: '3'

services:
  web:
    build: .
    command: bash -c "python manage.py migrate && python manage.py runserver"
    container_name: PerformanceTracker
    volumes:
      - .:/code
    ports:
      - "8000:8000"
    depends_on:
      - redis

  celery-worker:
    build: .
    command: celery -A PerformanceTracker worker --loglevel=info
    volumes:
      - .:/code
    depends_on:
      - redis

  celery-beat:
    build: .
    command: celery -A PerformanceTracker beat --loglevel=info
    volumes:
      - .:/code
    depends_on:
      - redis

  redis:
    image: redis:latest
    expose:
      - 6379
    ports:
      - '9999:6379'
