# Generated by Django 4.2.11 on 2024-04-18 05:28

from django.db import migrations, models
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        ('metrics', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='dailyperformance',
            managers=[
                ('dp', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AlterModelManagers(
            name='hourlyperformance',
            managers=[
                ('hp', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AlterField(
            model_name='dailyperformance',
            name='date',
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='hourlyperformance',
            name='datetime',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
